version: 1

config:
  company: "getsyncer"
  owner: "@getsyncer/maintainers"
  repush_on_actor: renovate[bot]


logic:
  - source: github.com/getsyncer/public-sync-modules/buildaction
  - source: github.com/getsyncer/public-sync-modules/gitignore
  - source: github.com/getsyncer/public-sync-modules/gosemanticrelease
  - source: github.com/getsyncer/public-sync-modules/lintworkflows
  - source: github.com/getsyncer/public-sync-modules/setlicense
  - source: github.com/getsyncer/public-sync-modules/synceractions
  - source: github.com/getsyncer/public-sync-modules/renovatebot

syncs:
  - logic: renovatebot
    config:
      extends:
        - "github>getsyncer/renovate-config"
  - logic: buildaction
  - logic: gitignore
  - logic: gosemanticrelease
  - logic: lintworkflows
  - logic: setlicense
    config:
      license: "Apache-2.0"
  - logic: synceractions
