version: 1

config:
  company: "getsyncer"
  owner: "@getsyncer/infrastructure-squad"

logic:
  - source: github.com/getsyncer/public-sync-modules/buildgolib
  - source: github.com/getsyncer/public-sync-modules/golangcilint
  - source: github.com/getsyncer/public-sync-modules/setlicense
  - source: github.com/getsyncer/public-sync-modules/synceractions

syncs:
  - logic: buildgolib
  - logic: golangcilint
  - logic: synceractions
  - logic: setlicense
    config:
      license: "Apache-2.0"