version: 1

config:
  company: "cresta"
  owner: @cresta/infrastructure-squad

logic:
  - source: github.com/cresta/public-sync-modules/autoapprove
  - source: github.com/cresta/public-sync-modules/buildgolib
  - source: github.com/cresta/public-sync-modules/golangcilint
  - source: github.com/cresta/public-sync-modules/setlicense

syncs:
  - logic: autoapprove
  - logic: buildgolib
  - logic: golangcilint
  - logic: setlicense
    config:
      license: "Apache-2.0"